apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://repo.app.ysoft.com/scm/aws/k8s-apps.git
    path: argocd/base/install
    targetRevision: argocd
  - repoURL: https://repo.app.ysoft.com/scm/aws/k8s-apps.git
    path: argocd/base/config
    targetRevision: argocd
  - repoURL: https://repo.app.ysoft.com/scm/aws/k8s-apps.git
    path: argocd/base/apps
    targetRevision: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
